name: demo

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Set environment variables
        run: |
          echo "DEMO=x" >> $GITHUB_ENV

      - name: a
        if: ${{ env.DEMO }} == "a"
        run: |
          echo a

      - name: b
        if: env.DEMO == 'b'
        run: |
          echo b

      - name: x
        if: env.DEMO == 'x'
        run: |
          echo x
